# Generated by Django 3.0.5 on 2020-05-09 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='about_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('expertise', models.TextField(max_length=15)),
                ('fb_link', models.CharField(max_length=100)),
                ('tw_link', models.CharField(max_length=100)),
                ('lk_link', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='member_pics')),
            ],
            options={
                'verbose_name': 'About Member',
                'verbose_name_plural': 'About Member',
            },
        ),
        migrations.CreateModel(
            name='home_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='slider_pics')),
                ('sliding_text', models.TextField(max_length=30)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.CreateModel(
            name='Service_Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('panno', models.CharField(max_length=30, unique=True)),
                ('about', models.TextField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=10, unique=True)),
                ('averageRating', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='sp_pics')),
                ('is_approved', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('Posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Provider',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=800)),
                ('rating', models.FloatField(default=0)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soc.Service_Provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
